class Color:
    BASIC_BG = '#f3f3f3'
    BASIC_FG = '#302833'
    BASIC_INNER_BG = 'white'
    BASIC_INNER_FG = '#433d3c'
    SELECT_BG = '#eaf4fc'
    SELECT_FG = '#302833'
    LINK_BG = 'white'
    LINK_FG = 'blue'
    LINK_VISITED_FG = 'purple'
